### ISSUE TITLE
Error creating the first tree record (level 0).

### ISSUE THREAD

**Issue by jpsepulvedaf** [fremail/sequelize-nested-set#9]
Hello,
During the testing process of this library, I encountered some problems when creating the first record of a tree. What you would expect when creating the first record of a tree, is that the library automatically manages the filling of the fields "lft", "rgt", "level", "root", and that only the other mandatory fields are completed. the entity. When trying to create the first record, request the fields "rootId" and "level".

I attach the code that replicates the error.

**/models/category.js**
```
'use strict';
const ns = require('sequelize-nested-set');
module.exports = (sequelize, DataTypes) => {
  const category = ns(sequelize, DataTypes, 'Category', {
    name: {
      type: DataTypes.STRING,
      allowNull: false,
      validate: {
        notEmpty: true,
      },
    },
  }, {
    underscored: true,
    freezeTableName: true,
    hasManyRoots: true,
    tableName: 'category',
    rootColumnName: 'root'
  });

  return category;

};
```

**/server.js**
```
var db = require('./models');
var Sequelize = require('sequelize');
const sequelize = new Sequelize({
    dialect: 'sqlite',
    storage: './finanzasdb.sqlite3'
});

db.sequelize.sync({force: true}).then(
    async function () {

        let category = await db.Category.create({
            type: 1,
            name: 'Root record',
            // rootId: 1,
            // level: 0
        });

    }
);
```

Then, when executing the file "server.js" the following error appears...

```
Unhandled rejection SequelizeValidationError: notNull Violation: Category.level cannot be null,
notNull Violation: Category.rootId cannot be null
    at Promise.all.then (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/sequelize/lib/instance-validator.js:74:15)
    at tryCatcher (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jpsepulvedaf/Desktop/nestedset-test/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
```

**Comment by fremail** [comment]
@jpsepulvedaf for creating a root record (the first tree record with level 0) there is a special function `createRoot(record, options)`. It handles setting left and right values, rootId and level.

Here is an example of using it:
```javascript
let category = new db.Category();
category.name = 'Root record';
category = await db.Category.createRoot(category);
```

I hope this helps you!

**Comment by jpsepulvedaf** [comment]
Ooooo true, thank you very much!
I tried to create the registry but from a JSON, that's why the creation failed me
;)
